### ISSUE TITLE
test

### ISSUE THREAD

**Issue by g4s8** [g4s8/RxKeyboard#4]
test

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322979314))

@g4s8 Job `gh:g4s8/rxkeyboard#4` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1215](http://www.0crat.com/u/g4s8).

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322980480))

@g4s8 Job `gh:g4s8/rxkeyboard#4` is now out of scope.

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322980527))

@g4s8 Job `gh:g4s8/rxkeyboard#4` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1230](http://www.0crat.com/u/g4s8).

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322981311))

@g4s8 Hey, what's up, how is it going?

**Comment by g4s8** [comment]
@0crat assign 0crat

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168)
	at com...
```

**Comment by 0crat** [comment]
Job `gh:g4s8/rxkeyboard#4` assigned to @0crat, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
> @0crat assign 0crat ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322981557))

@g4s8 Argument "0crat" doesn't match regex "me|@[a-zA-Z0-9\-]+"

**Comment by 0crat** [comment]
Job `gh:g4s8/rxkeyboard#4` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @0crat, total is [+30](http://www.0crat.com/u/0crat).

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/g4s8/RxKeyboard/issues/4#issuecomment-322983491))

@g4s8 I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2f52b52 2017-08-17T05:56:32
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:g4s8/rxkeyboard#4` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$2.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactiv...
```
